### ISSUE TITLE
May I ask when will the code be released

### ISSUE THREAD

**Issue by yangrongkun** [V-DETR/V-DETR#1]
Hi, yichaoshen. Thank you for your wonderful work, the position information encoding of V-DETR is innovative, and I’m interested in the detail implementation, could the code be released? 
Thank you very much!

**Comment by auniquesun** [comment]
Me too, look forward to the code release!

**Comment by mostafa501** [comment]
+1

**Comment by CodeWZT** [comment]
hi, congratulation for your paper accepted by ICLR 2024, looking forward to the code release.

**Comment by yichaoshen-MS** [comment]
Our code will be released very soon, most likely within 1-2 weeks. Additionally, while cleaning up the code, we optimized our code, and there are some indications that our model may perform better. Please look forward to it. Thank you for your understanding.

**Comment by zyh16143998882** [comment]
Thanks for your great work and previous replies, I was wondering how soon I can access to your code now.

**Comment by weiguangzhao** [comment]
Look forward to the code release!

**Comment by yxchng** [comment]
m

**Comment by CCFish151** [comment]
Look forward to the code release!

**Comment by PkuRainBow** [comment]
Hi All, @yichaoshen-MS is a research intern that is responsible for the code release.

He will help releasing the code in the coming weeks.
