### ISSUE TITLE
About the code

### ISSUE THREAD

**Issue by zhuhean** [V-DETR/V-DETR#2]
This paper has been accepted by ICLR 2024, and this project has been open-sourced for six months. However, the authors do not seem to intend to open-source the code or respond to any questions. I think this project has lost its meaning of existence.

**Comment by yichaoshen-MS** [comment]
Our code will be released very soon, most likely within 1-2 weeks. Additionally, while cleaning up the code, we optimized our code, and there are some indications that our model may perform better. Please look forward to it. Thank you for your understanding.
