### ISSUE TITLE
Questions about 'scannet_utils' is absent and the difference of 'batch_load_scannet_data' from original

### ISSUE THREAD

**Issue by jkstyle2** [V-DETR/V-DETR#8]
Hello, thanks for sharing your great work.

I tried your project with ScanNet dataset which was previously processed from VoteNet's [batch_load_scannet_data](https://github.com/facebookresearch/votenet/blob/main/scannet/batch_load_scannet_data.py). The name of output folder is same as yours, so I thought they have same results.

However, the evaluation result that I got with your model is as below. It is much different from your released result. I used [the ckpt](https://huggingface.co/byshen/vdetr/blob/main/scannet_540ep.pth). 

```
====================
Test model; Metrics mAP0.25, mAP0.50: 70.17, 57.65
AR0.25, AR0.50: 92.27, 78.75
```

And now, I noticed there is a slight difference in line47-51 from [batch_load_scannet_data](https://github.com/facebookresearch/votenet/blob/main/scannet/batch_load_scannet_data.py#L47-L51), which is deleted in [yours](https://github.com/V-DETR/V-DETR/blob/main/scannet/batch_load_scannet_data.py). 
Is there a possibility to affect to the evaluation result? It seems that the results are quite different (77.85->70.17 mAP@0.25)

To achieve the result you reported, should I used [yours](https://github.com/V-DETR/V-DETR/blob/main/scannet/batch_load_scannet_data.py) ? There is also 'scannet_utils' missing.

**Comment by yichaoshen-MS** [comment]
Yes, the max number of point clouds in Votenet is 40k~50k. This setting is seemed to be outmoded, so after Fcaf3d, nowadays works, (include VDETR, cagroup3d), usually use more points like 100k points, please process the dataset according to the readme.
